server:
  port: 8761
eureka:
  instance:
    hostname: eureka-server  # eureka实例的主机名, 必须参照域名的命名标准，不能有下划线_，否则客户端无法连接
  client:
    register-with-eureka: false #不把自己注册到eureka上
    fetch-registry: false #不从eureka上来获取服务的注册信息
    service-url:
      defaultZone: http://localhost:8761/eureka/