#for dubbo 2.x
dubbo:
  application:
    name: springboot-dubbo_consumer-user
    id: springboot-dubbo_consumer-user
  registry:
    address: zookeeper://127.0.0.1:2181
    group: springboot
    timeout: 5000